export const music = [
	{
		id: 1,
		artist: 'Avantdale Bowling Club',
		album: 'Trees',
		year: '2022',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 47,
		quantity: '10',
		stripe_product_id: 'prod_NIpyio4t6v7qrr',
		stripe_price_id: 'price_1MbAaeEDyCcN2QeKjClqDypK',
	},
	{
		id: 2,
		artist: 'A Tribe Called Quest',
		album: 'Low End Theory',
		year: '1991',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 60,
		quantity: '3',
		stripe_product_id: 'prod_NIpzggdcqdBKvZ',
		stripe_price_id: 'price_1MbAb3EDyCcN2QeKAFjPlFrZ',
	},
	{
		id: 3,
		artist: 'Blu & Exile',
		album: 'Below the Heavens',
		year: '2007',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 47,
		quantity: '5',
		stripe_product_id: 'prod_NIq0Tc6Hw60Af1',
		stripe_price_id: 'price_1MbAbxEDyCcN2QeKNH3hnyUO',
	},
	{
		id: 4,
		artist: 'Ivan Ave',
		album: 'Double Goodbyes',
		year: '2020',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 47,
		quantity: '10',
		stripe_product_id: 'prod_NIq0600ae5bU0s',
		stripe_price_id: 'price_1MbAcJEDyCcN2QeKuePsgf4w',
	},
	{
		id: 5,
		artist: 'J Dilla',
		album: 'Donuts',
		year: '2006',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 59,
		quantity: '5',
		stripe_product_id: 'prod_NIq0pVak8xRRcw',
		stripe_price_id: 'price_1MbAcmEDyCcN2QeKLQYgCJ59',
	},
	{
		id: 6,
		artist: 'Kofi Stone',
		album: 'Nobody Cares Till Everybody Does',
		year: '2019',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 44,
		quantity: '5',
		stripe_product_id: 'prod_NIq1oAcTQQySX3',
		stripe_price_id: 'price_1MbAdGEDyCcN2QeKQIpEJTyp',
	},
	{
		id: 7,
		artist: 'Little Brother',
		album: 'The Listening',
		year: '2003',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 54,
		quantity: '10',
		stripe_product_id: 'prod_NIq14WuuQL0n7s',
		stripe_price_id: 'price_1MbAdVEDyCcN2QeKrIUbS0zP',
	},
	{
		id: 8,
		artist: 'Nas',
		album: 'Illmatic',
		year: '1994',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 47,
		quantity: '3',
		stripe_product_id: 'prod_NIq1LrK6fzo2wQ',
		stripe_price_id: 'price_1MbAdmEDyCcN2QeKTT70fY6z',
	},
	{
		id: 9,
		artist: 'People Under The Stairs',
		album: 'O.S.T',
		year: '2002',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 58,
		quantity: '2',
		stripe_product_id: 'prod_NIpyfpe6h25wPO',
		stripe_price_id: 'price_1MbAeAEDyCcN2QeKYtWQoK8O',
	},
	{
		id: 10,
		artist: 'Royal Flush',
		album: 'Ghetto Millionaire',
		year: '1997',
		genre: 'hip-hop/rap',
		description: 'description',
		price: 47,
		quantity: '1',
		stripe_product_id: 'prod_NIq2uuZuf9ZKfd',
		stripe_price_id: 'price_1MbAePEDyCcN2QeKWt4t6wWz',
	},
	{
		id: 11,
		artist: 'Amen Dunes',
		album: 'Freedom',
		year: '2018',
		genre: 'Indie/Alternative',
		description: 'description',
		price: 47,
		quantity: '10',
		stripe_product_id: 'prod_NIq2u3wDmFHTHt',
		stripe_price_id: 'price_1MbAejEDyCcN2QeKak5FDYHK',
	},
	{
		id: 12,
		artist: 'Beach Fossils',
		album: 'Somersault',
		year: '2017',
		genre: 'Indie/Alternative',
		description: 'description',
		price: 47,
		quantity: '7',
		stripe_product_id: 'prod_NIq2wGBSlS4sfx',
		stripe_price_id: 'price_1MbAexEDyCcN2QeKdTkRiZCA',
	},
	{
		id: 13,
		artist: 'Do Nothing',
		album: 'Zero Dollar Bill',
		year: '2020',
		genre: 'Indie/Alternative',
		description: 'description',
		price: 47,
		quantity: '4',
		stripe_product_id: 'prod_NIq3arDbvpK1J7',
		stripe_price_id: 'price_1MbAfIEDyCcN2QeK5vEv2tnQ',
	},
	{
		id: 14,
		artist: 'Floodlights',
		album: 'From a View',
		year: '2020',
		genre: 'Indie/Alternative',
		description: 'description',
		price: 42,
		quantity: '5',
		stripe_product_id: 'prod_NIq3qtv5veZHSv',
		stripe_price_id: 'price_1MbAfXEDyCcN2QeKoQDp3WiG',
	},
	{
		id: 15,
		artist: 'Fontaines D.C.',
		album: 'Dogrel',
		year: '2019',
		genre: 'Post-punk',
		description: 'description',
		price: 47,
		quantity: '7',
		stripe_product_id: 'prod_NIq4Pks4UN3nH9',
		stripe_price_id: 'price_1MbAfoEDyCcN2QeKhSMwMlUn',
	},
	{
		id: 16,
		artist: 'Idles',
		album: 'Joy as an Act of Resistance',
		year: '2018',
		genre: 'Punk Rock',
		description: 'description',
		price: 47,
		quantity: '7',
		stripe_product_id: 'prod_NIq4o5waf6YJOK',
		stripe_price_id: 'price_1MbAg6EDyCcN2QeK5eQICSU7',
	},
	{
		id: 17,
		artist: 'Parquet Courts',
		album: 'Light Up Gold',
		year: '2012',
		genre: 'Indie/Alternative',
		description: 'description',
		price: 47,
		quantity: '4',
		stripe_product_id: 'prod_NIq5ao4LcclVF1',
		stripe_price_id: 'price_1MbAgSEDyCcN2QeKPVk7jyyf',
	},
	{
		id: 18,
		artist: 'Parquet Courts',
		album: 'Wide Awake',
		year: '2018',
		genre: 'Indie/Alternative',
		description: 'description',
		price: 47,
		quantity: '7',
		stripe_product_id: 'prod_NIq5fOTBRL3kvZ',
		stripe_price_id: 'price_1MYEPOEDyCcN2QeKTnkZYVhV',
	},
	{
		id: 19,
		artist: 'The Slingers',
		album: 'One More Day / This Time',
		year: '2017',
		genre: 'Indie/Alternative',
		description: 'description',
		price: 35,
		quantity: '3',
		stripe_product_id: 'prod_NIq53cj7kqtfxe',
		stripe_price_id: 'price_1MbAgrEDyCcN2QeK06sQD4Fj',
	},
	{
		id: 20,
		artist: 'Yard Act',
		album: 'The Overload',
		year: '2022',
		genre: 'Indie/Alternative',
		description: 'description',
		price: 47,
		quantity: '7',
		stripe_product_id: 'prod_NIq6WHFY9idwEP',
		stripe_price_id: 'price_1MYEQ3EDyCcN2QeKKd4anTav',
	},
];
